#server
server:
  port: 9090
  tomcat:
    uri-encoding: UTF-8  

#spring
spring:
  datasource:
    url: jdbc:mysql://192.168.10.188:3306/test?characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  #jpa
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  #redis
  redis:
    #database:9
    host: 192.168.10.188
    port: 6379
    #password: 123456
    database: 9
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8 
      max-wait: -1
